
CPU_MODEL ?= f446e
#### CPU-dependent source files 
CONTIKI_CPU_SOURCEFILES += soc.c clock.c rtimer-arch.c uart.c watchdog.c 

#### This is what will actually instruct the system to build all of the above
CONTIKI_SOURCEFILES += $(CONTIKI_CPU_SOURCEFILES) $(DEBUG_IO_SOURCEFILES)
CONTIKI_SOURCEFILES += $(USB_SOURCEFILES)

# F4 MCU Headers
CFLAGS += -I$(CONTIKI_NG_ARCH_CPU_DIR)/stm32f4xx
CFLAGS += -I$(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/$(CPU_MODEL)

include $(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/f446re/Makefile.f446
include $(CONTIKI)/$(CONTIKI_NG_CM4_DIR)/Makefile.cm4
