
CPU_MODEL ?= f446re

#### CPU-dependent source files - just filenames, build system finds them in CONTIKI_CPU_DIRS
CONTIKI_CPU_SOURCEFILES += soc.c
CONTIKI_CPU_SOURCEFILES += system_stm32f4xx.c 
CONTIKI_CPU_SOURCEFILES += startup_stm32f446re.c

#### This is what will actually instruct the system to build all of the above
CONTIKI_SOURCEFILES += $(CONTIKI_CPU_SOURCEFILES) $(DEBUG_IO_SOURCEFILES)
CONTIKI_SOURCEFILES += $(USB_SOURCEFILES)

# F4 MCU Headers
CFLAGS += -I$(CONTIKI_NG_ARCH_CPU_DIR)/stm32f4xx
CFLAGS += -I$(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/$(CPU_MODEL)

# Device-specific configuration - use absolute path so make can find the linker script
LDSCRIPT ?= $(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/$(CPU_MODEL)/stm32f446re.ld
CFLAGS += -DSTM32F446xx

include $(CONTIKI)/$(CONTIKI_NG_CM4_DIR)/Makefile.cm4