# Extra source files that are ONLY for STM32F446RE

# Linker script and startup for this exact MCU
LDSCRIPT ?= $(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/f446re/stm32f446re.ld
CONTIKI_SOURCEFILES += $(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/f446re/startup_stm32f446re.c

# Model-specific CFLAGS (define the exact chip, enable HAL if you use it, etc.)
CFLAGS += -DSTM32F446xx
# CFLAGS += -DUSE_HAL_DRIVER  # if you wire in STM32 HAL
# Add any per-MCU include dirs here as needed
# CFLAGS += -I$(CONTIKI_NG_RELOC_CPU_DIR)/stm32f4xx/f446re


